version: '3.7'

services:
  gateway:
    image: nginx:latest
    container_name: gateway
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./volumes/gateway/confs:/etc/nginx/conf.d
      - ./volumes/front-end/dist:/www/data

  front-end:
    image: node:latest
    container_name: front-end
    restart: always
    working_dir: /app
    command: "sh app-setup.sh"
    volumes:
      - ./volumes/front-end:/app
